### ISSUE TITLE
Error `itemAction`

### ISSUE THREAD

**Issue by nabezokodaikon** [Shougo/ddu-ui-std#1]
**Warning: I will close the issue without the minimal init.vim and the
reproduction instructions.**

# Problems summary
When I execute itemAction in the ddu buffer, I get an error.

## Expected
The file is opened when itemAction is executed.

## Environment Information

- ddu-ui-std version (SHA1):47bbb8801d93698401bde4d9ac1409ab04f3809c

- ddu.vim version (SHA1):8e21a4a41ead8d1531051483f248209b19f5501a

- denops.vim version (SHA1):333aa1783352c346cc4fbaa43217bbc1c07ddbaa

- deno version(`deno -V` output):1.18.1

- OS:Mac

- neovim/Vim `:version` output:v0.7.0-dev+956-g6cb670cb2

- `:checkhealth` or `:CheckHealth` result(neovim only):OK

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
if &compatible
    set nocompatible
endif

let $CACHE = expand('~/.cache')

if !isdirectory(expand($CACHE))
    call mkdir(expand($CACHE), 'p')
endif

let s:dein_dir = expand('$CACHE/dein')
let s:dein_repo_dir = s:dein_dir . '/repos/github.com/Shougo/dein.vim'

if &runtimepath !~# '/dein.vim'
    if !isdirectory(s:dein_repo_dir)
        execute '!git clone https://github.com/Shougo/dein.vim' s:dein_repo_dir
    endif
    execute 'set runtimepath^=' . s:dein_repo_dir
endif

call dein#begin(s:dein_dir, expand('<sfile>'))

call dein#add('vim-denops/denops.vim')
call dein#add('Shougo/ddu.vim')
call dein#add('Shougo/ddu-commands.vim')
call dein#add('Shougo/ddu-ui-std')
call dein#add('Shougo/ddu-filter-matcher_substring')
call dein#add('Shougo/ddu-source-file_rec')

call dein#end()
call dein#save_state()

call ddu#custom#patch_global({
    \   'ui': 'std',
    \   'sourceOptions': {
    \     '_': {
    \       'ignoreCase': v:true,
    \       'matchers': ['matcher_substring'],
    \     },
    \   },
    \ })

autocmd FileType ddu-std call s:ddu_my_settings()
function! s:ddu_my_settings() abort
  nnoremap <buffer><silent> <CR>
  \ <Cmd>call ddu#ui#std#do_action('itemAction')<CR>
  nnoremap <buffer><silent> i
  \ <Cmd>call ddu#ui#std#do_action('openFilterWindow')<CR>
  nnoremap <buffer><silent> q
  \ <Cmd>call ddu#ui#std#do_action('quit')<CR>
endfunction

autocmd FileType ddu-std-filter call s:ddu_filter_my_settings()
function! s:ddu_filter_my_settings() abort
  inoremap <buffer><silent> <CR>
  \ <Esc><Cmd>close<CR>
  nnoremap <buffer><silent> <CR>
  \ <Cmd>close<CR>
endfunction
```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. Run `call dein#update()` command.
2. Restart Neovim
3. Run `Ddu -name=search file_rec -ui-param-startFilter=v:true` command.
4. Select an item and press the enter key.

## Screenshot (if possible)
![スクリーンショット 2022-01-29 16 40 15](https://user-images.githubusercontent.com/3197942/151652353-9eeea1e8-0505-49d1-bfe9-aec784e2e258.png)

**Comment by nabezokodaikon** [comment]
I'm created PR.
https://github.com/Shougo/ddu.vim/pull/5#issue-1118257321

**Comment by Shougo** [comment]
Sorry.  Fixed.

**Comment by nabezokodaikon** [comment]
Thank you.
