### ISSUE TITLE
`<C-j>` hides the prompt.

### ISSUE THREAD

**Issue by nabezokodaikon** [Shougo/ddu-ui-std#10]
**Warning: I will close the issue without the minimal init.vim and the
reproduction instructions.**

# Problems summary
`<C-j>` hides the prompt.

## Expected
`<C-j>` does not hide the prompt.

## Environment Information

- ddu-ui-std version (SHA1): f9a5f27a1d45a5672fa613404277bebe1e399174

- ddu.vim version (SHA1): 8a765f0ab1d1235e51a6853bcc900c4a42134382

- denops.vim version (SHA1): e2f17041495123e8ed9baa69098c947c5d7f6358

- deno version(`deno -V` output): 1.18.2

- OS: Mac

- neovim/Vim `:version` output:
```
NVIM v0.7.0-dev+1017-g28d5face2
Build type: Release
LuaJIT 2.1.0-beta3
```

- `:checkhealth` or `:CheckHealth` result(neovim only): OK

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
if &compatible
    set nocompatible
endif

let $CACHE = expand('~/.cache')

if !isdirectory(expand($CACHE))
    call mkdir(expand($CACHE), 'p')
endif

let s:dein_dir = expand('$CACHE/dein')
let s:dein_repo_dir = s:dein_dir . '/repos/github.com/Shougo/dein.vim'

if &runtimepath !~# '/dein.vim'
    if !isdirectory(s:dein_repo_dir)
        execute '!git clone https://github.com/Shougo/dein.vim' s:dein_repo_dir
    endif
    execute 'set runtimepath^=' . s:dein_repo_dir
endif

call dein#begin(s:dein_dir, expand('<sfile>'))

call dein#add('vim-denops/denops.vim')
call dein#add('Shougo/ddu.vim')
call dein#add('Shougo/ddu-commands.vim')
call dein#add('Shougo/ddu-ui-std')
call dein#add('Shougo/ddu-filter-matcher_substring')
call dein#add('Shougo/ddu-source-file_rec')
call dein#add('Shougo/ddu-kind-file')

call dein#end()
call dein#save_state()

call ddu#custom#patch_global({
    \   'ui': 'std',
    \   'sourceOptions': {
    \     '_': {
    \       'matchers': ['matcher_substring'],
    \     },
    \   },
    \   'uiParams': {
    \     'std': {
    \       'split': 'floating',
    \       'prompt': '>'
    \     },
    \   },
    \ })

autocmd FileType ddu-std call s:ddu_my_settings()
function! s:ddu_my_settings() abort
  nnoremap <buffer><silent> <CR>
  \ <Cmd>call ddu#ui#std#do_action('itemAction')<CR>
  nnoremap <buffer><silent> i
  \ <Cmd>call ddu#ui#std#do_action('openFilterWindow')<CR>
  nnoremap <buffer><silent> q
  \ <Cmd>call ddu#ui#std#do_action('quit')<CR>
endfunction

autocmd FileType ddu-std-filter call s:ddu_filter_my_settings()
function! s:ddu_filter_my_settings() abort
  inoremap <buffer><silent> <CR>
  \ <Esc><Cmd>close<CR>
  nnoremap <buffer><silent> <CR>
  \ <Cmd>close<CR>
endfunction
```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. Start Neovim.
2. Run `call dein#update()` commnad.
3. Restart Neovim.
4. Run `call ddu#start({'sources': [{'name': 'file_rec'}]})` command.
5. Type `i` (Open filter)
6. Type `<C-j>`

## Screenshot (if possible)
![スクリーンショット 2022-02-06 20 16 05](https://user-images.githubusercontent.com/3197942/152678217-65b8f4f7-e114-4ff0-9333-869ed474ef46.png)

**Comment by Shougo** [comment]
Fixed.

**Comment by nabezokodaikon** [comment]
I have confirmed that `<C-j>` does not hide the prompt.

But now, I found that pressing `Shift + O` hides the prompt under the same conditions.

**Comment by Shougo** [comment]
Fixed.  Please use the latest.

**Comment by nabezokodaikon** [comment]
The following steps will make it disappear again.

1. Run `call ddu#start({'sources': [{'name': 'file_rec'}]})` command.
2. Open filter.
3. Input word.
4. Close filter (Press Enter key)
5. Open filter.

![スクリーンショット 2022-02-07 11 16 41](https://user-images.githubusercontent.com/3197942/152714509-929e4091-7146-4aa5-9132-cb88d9303389.png)

![スクリーンショット 2022-02-07 11 16 50](https://user-images.githubusercontent.com/3197942/152714508-afedaffe-f587-40f5-91a2-a7eb862f3245.png)

![スクリーンショット 2022-02-07 11 16 59](https://user-images.githubusercontent.com/3197942/152714505-9bafc11a-4b7d-47b5-964a-6b79157da2c7.png)

**Comment by Shougo** [comment]
Fixed.

**Comment by nabezokodaikon** [comment]
Confirmed. Thank you.

**Comment by nabezokodaikon** [comment]
Is it a specification that past filter keywords are displayed when the filter is set to normal mode and `k` is pressed?

**Comment by Shougo** [comment]
Yes.  It is same behavior with denite.nvim.

**Comment by nabezokodaikon** [comment]
So that's it. understand. thank you.
