### ISSUE TITLE
[Question] What happens when the filter closes.

### ISSUE THREAD

**Issue by nabezokodaikon** [Shougo/ddu-ui-std#5]
I have some processing that I want to execute at the same time as the filter closes. Is there any processing that is executed when the filter closes (hides)?

## Environment Information

- ddu-ui-std version (SHA1): cc8ea7818e1e6a09d574736e662e69971f0658e2

- ddu.vim version (SHA1): e876d13b656a35232fa9f371a9c9cc9ba2a09f5d

- denops.vim version (SHA1): e2f17041495123e8ed9baa69098c947c5d7f6358

- deno version(`deno -V` output): 1.18.1

- OS: Mac

- neovim/Vim `:version` output: v0.7.0-dev+984-g2870311a3

- `:checkhealth` or `:CheckHealth` result(neovim only): OK

**Comment by Shougo** [comment]
You can use `WinClosed` for it.

```
							*WinClosed*
WinClosed			After closing a window.  The pattern is
				matched against the |window-ID|.  Both
				<amatch> and <afile> are set to the |window-ID|.
				After WinLeave.
				Non-recursive (event cannot trigger itself).
				See also |ExitPre|, |QuitPre|.
```

**Comment by Shougo** [comment]
You should save winid in `Filetype ddu-std-filter`.

**Comment by nabezokodaikon** [comment]
Thank you for telling me.
